'use strict';
(()=>{
const geo=window.MAP_DATA,svg=document.getElementById('brooklyn-map'),ns='http://www.w3.org/2000/svg';
const marks=new Map(),bubbles=new Map();let currentView='map',selected=null,box=[0,0,760,640];
const make=(tag,attrs,parent=svg)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs||{}).forEach(([k,v])=>n.setAttribute(k,v));parent.append(n);return n;};
const defs=make('defs'),pattern=make('pattern',{id:'excluded-pattern',width:7,height:7,patternUnits:'userSpaceOnUse'},defs);make('rect',{width:7,height:7,fill:'#f4f4ed'},pattern);make('path',{d:'M0,7L7,0',stroke:'#a6afaa','stroke-width':1.5},pattern);
make('path',{d:geo.context,fill:'#dce5e3',stroke:'#f3f7f6','stroke-width':.6,'fill-rule':'evenodd','pointer-events':'none'});
const regions=make('g',{class:'regions'}),circles=make('g',{class:'map-circles'}),labels=make('g',{'pointer-events':'none'});
geo.labels.forEach(l=>{const t=make('text',{x:l.point[0],y:l.point[1],class:'context-label','text-anchor':'middle'},labels);t.textContent=l.text;});
const setBox=b=>{box=b;svg.setAttribute('viewBox',box.join(' '));};
const focusArea=(a,zoom=false)=>{selected=a;inspect(a,state.cuisine);if(zoom){const g=geo.areas.find(g=>g.name===a.name),b=g.bounds,w=Math.max(220,(b[2]-b[0])*2,(b[3]-b[1])*2*760/640),h=w*640/760;setBox([(b[0]+b[2]-w)/2,(b[1]+b[3]-h)/2,w,h]);}updateSelection(a);};
function updateSelection(a){marks.forEach((n,name)=>n.classList.toggle('map-selected',name===a.name));bubbles.forEach((n,name)=>n.classList.toggle('map-selected',name===a.name));$('map-readout').textContent=`${a.name} · ${cuisines[state.cuisine]}: ${pct(share(a,state.cuisine))} · ${num(a.counts[state.cuisine])} of ${num(a.total)} restaurants`;}
geo.areas.forEach(g=>{const a=areas.find(a=>a.name===g.name);const p=make('path',{d:g.path,'fill-rule':'evenodd',class:a?'map-region':'map-excluded','vector-effect':'non-scaling-stroke',tabindex:0,role:'button'},regions);marks.set(g.name,p);const title=make('title',{},p);
if(a){const b=make('circle',{cx:g.center[0],cy:g.center[1],r:0,class:'map-bubble','pointer-events':'none','vector-effect':'non-scaling-stroke'},circles);bubbles.set(g.name,b);p.addEventListener('pointerenter',e=>{if(e.pointerType!=='touch'){inspect(a,state.cuisine);updateSelection(a);}});p.addEventListener('focus',()=>{inspect(a,state.cuisine);updateSelection(a);});p.addEventListener('click',()=>{if(!dragged)focusArea(a);});p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focusArea(a,true);}});
}else{p.setAttribute('fill','url(#excluded-pattern)');const message=`${g.name}, ZIP ${g.zips.join(', ')}: not included; fewer than 30 restaurants in the cleaned sample.`;p.setAttribute('aria-label',message);title.textContent=message;const show=()=>{$('map-readout').textContent=message;};p.addEventListener('pointerenter',show);p.addEventListener('focus',show);p.addEventListener('click',show);p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show();}});}});
function renderMap(){const max=Math.max(...areas.map(a=>value(a,state.cuisine)));$('map-title').textContent=`${cuisines[state.cuisine]} across Brooklyn`;$('map-caption').textContent=state.metric==='share'?'Darker areas mean a larger share of local restaurants. Hover, tap, or focus an area for details.':'Circle area represents restaurant count. Positions identify ZIP-based areas, not individual restaurants.';
$('map-legend').replaceChildren();const legend=$('map-legend');if(state.metric==='share'){legend.append(el('span','Share of local restaurants'),el('span','0%'),el('span',undefined,'gradient'),el('span',pct(max)));}else{legend.append(el('span','Circle area = restaurant count'));[.25,.5,1].forEach(f=>{const n=Math.max(1,Math.round(max*f)),item=el('span',undefined,'size-key'),circle=el('i');circle.style.width=circle.style.height=`${56*Math.sqrt(n/max)}px`;item.append(circle,el('span',num(n)));legend.append(item);});}legend.append(el('span','Not included','excluded-key'));
areas.forEach(a=>{const p=marks.get(a.name),b=bubbles.get(a.name),v=value(a,state.cuisine),t=max?v/max:0;const start=[237,246,242],end=[8,105,94];p.setAttribute('fill',state.metric==='share'?`rgb(${start.map((x,i)=>Math.round(x+(end[i]-x)*t)).join(',')})`:'#e5efea');b.setAttribute('r',state.metric==='count'?28*Math.sqrt(t):0);const label=`${a.name}, ZIP ${a.zips.join(', ')}. ${cuisines[state.cuisine]}: ${pct(share(a,state.cuisine))}; ${a.counts[state.cuisine]} of ${a.total} restaurants.`;p.setAttribute('aria-label',label);p.querySelector('title').textContent=label;});
const a=selected||sortAreas()[0];updateSelection(a);if(currentView==='map')inspect(a,state.cuisine);}
function changeView(v){currentView=v;['matrix','map'].forEach(name=>{const yes=v===name;$(name+'-view').hidden=!yes;$(name+'-tab').setAttribute('aria-selected',String(yes));$(name+'-tab').tabIndex=yes?0:-1;});if(v==='map')renderMap();else if(selected)inspect(selected,state.cuisine);}
['matrix','map'].forEach(v=>{const tab=$(v+'-tab');tab.addEventListener('click',()=>changeView(v));tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'map':e.key==='End'?'matrix':v==='map'?'matrix':'map';changeView(next);$(next+'-tab').focus();}});});
function zoom(f){const w=Math.max(190,Math.min(760,box[2]*f)),h=w*640/760;setBox([box[0]+(box[2]-w)/2,box[1]+(box[3]-h)/2,w,h]);}
$('map-zoom-in').addEventListener('click',()=>zoom(.7));$('map-zoom-out').addEventListener('click',()=>zoom(1/.7));$('map-fit').addEventListener('click',()=>setBox([0,0,760,640]));
let drag=null,dragged=false;svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragged=false;drag={x:e.clientX,y:e.clientY,box:[...box]};});svg.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5){dragged=true;svg.setPointerCapture(e.pointerId);const k=drag.box[2]/svg.getBoundingClientRect().width;setBox([drag.box[0]-dx*k,drag.box[1]-dy*k,drag.box[2],drag.box[3]]);}});svg.addEventListener('pointerup',()=>{drag=null;});svg.addEventListener('pointercancel',()=>{drag=null;});
window.addEventListener('spotlight:render',renderMap);window.addEventListener('spotlight:inspect',e=>{if(currentView==='map')updateSelection(e.detail.area);});
window.mapExplorer={isActive:()=>currentView==='map',selectArea:a=>focusArea(a,true),reset(){selected=null;setBox([0,0,760,640]);renderMap();}};
changeView('map');
})();
